In [ ]:
import numpy as np
import pandas as pd

In [49]:
from google.colab import files
uploaded = files.upload()

Saving Consultores.xlsx to Consultores (1).xlsx
Saving Lojas.xlsx to Lojas (1).xlsx
Saving Metas.xlsx to Metas (1).xlsx
Saving Vendas.xlsx to Vendas (1).xlsx
Saving Vendas_2T.xlsx to Vendas_2T (1).xlsx

In [ ]:
consultores = pd.read_excel('Consultores.xlsx')

In [ ]:
lojas = pd.read_excel('Lojas.xlsx')

In [ ]:
metas = pd.read_excel('Metas.xlsx')

In [ ]:
vendas1T= pd.read_excel('Vendas.xlsx')
vendas2T= pd.read_excel('Vendas_2T.xlsx')

In [ ]:
lojas.head()

   IdStore                Store    Size State
0      284      San Diego Store  MEDIUM    CA
1      283  San Francisco Store  MEDIUM    CA
2      282        Angeles Store  MEDIUM    CA
3      285     Sacramento Store   SMALL    CA
4      320         Denver Store   LARGE    CO

In [ ]:
print(lojas.isnull())

    IdStore  Store   Size  State
0     False  False  False  False
1     False  False  False  False
2     False  False  False  False
3     False  False  False  False
4     False  False  False  False
5     False  False  False  False
6     False  False  False  False
7     False  False  False  False
8     False  False  False  False
9     False  False  False  False
10    False  False  False  False
11    False  False  False  False
12    False  False  False  False
13    False  False  False  False
14    False  False  False  False
15    False  False  False  False
16    False  False  False  False
17    False  False  False  False
18    False  False  False  False
19    False  False  False  False
20    False  False  False  False
21    False  False  False  False
22    False  False  False  False
23    False  False  False  False
24    False  False  False  False
25    False  False  False  False
26    False  False  False  False
27    False  False  False  False
28    False  False  False  False
29    False  False  False  False
30    False  False  False  False
31    False  False  False  False
32    False  False  False  False
33    False  False  False  False
34    False  False  False  False
35    False  False  False  False
36    False  False  False  False
37    False  False  False  False
38    False  False  False  False
39    False  False  False  False
40    False  False  False  False
41    False  False  False  False
42    False  False  False  False
43    False  False  False  False
44    False  False  False  False
45    False  False  False  False
46    False  False  False  False

In [ ]:
lojas["IdStore"].duplicated().sum()

np.int64(0)

In [ ]:
lojas['Size'].value_counts()

Size
MEDIUM    21
SMALL     13
LARGE      9
LRGE       1
MID        1
MEDIUN     1
SMAL       1
Name: count, dtype: int64

In [ ]:
lojas["Size"] = lojas["Size"].replace({
    "SMAL" : "SMALL",
    "MEDIUN" : "MEDIUM",
    "MID" : "MEDIUM",
    "LRGE" : "LARGE"
})

In [ ]:
lojas['Size'].value_counts()

Size
MEDIUM    23
SMALL     14
LARGE     10
Name: count, dtype: int64

Em lojas, não foi necessário checar por duplicidade de lojas, pois o IdStore não são duplicados. Houve o ajuste da escrita dos objeto Size, checagem de valores nulos e contagem

**Tratamento Consultores**

In [ ]:
consultores.head()

   IdSeller            Seller  IdStore              Role  Wage
0         1    Aaliyah Harris      358  Sales consultant  1400
1         2     Aaliyah Lewis      783  Sales consultant  1400
2         3    Aaliyah Morris      655  Sales consultant  1400
3         4  Aaliyah Williams      282     Sales Manager  2500
4         5     Abigail Allen      331  Sales consultant  1400

In [ ]:
consultores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 473 entries, 0 to 472
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   IdSeller  473 non-null    int64
 1   Seller    473 non-null    object
 2   IdStore   473 non-null    int64
 3   Role      473 non-null    object
 4   Wage      473 non-null    int64
dtypes: int64(3), object(2)
memory usage: 18.6+ KB

In [ ]:
print(consultores.isnull())

     IdSeller  Seller  IdStore   Role   Wage
0       False   False    False  False  False
1       False   False    False  False  False
2       False   False    False  False  False
3       False   False    False  False  False
4       False   False    False  False  False
..        ...     ...      ...    ...    ...
468     False   False    False  False  False
469     False   False    False  False  False
470     False   False    False  False  False
471     False   False    False  False  False
472     False   False    False  False  False

[473 rows x 5 columns]

In [ ]:
consultores['Role'].value_counts()

Role
Sales consultant    426
Sales Manager        47
Name: count, dtype: int64

In [ ]:
consultores["IdSeller"].duplicated().sum()

np.int64(3)

In [ ]:
duplicados_id = consultores[consultores.duplicated(subset=["IdSeller"], keep=False)]
display(duplicados_id)

     IdSeller           Seller  IdStore              Role  Wage
324       319     Mateo Turner      354  Sales consultant  1400
325       319     Mateo Turner      354     Sales Manager  2500
448       437  William Johnson      784  Sales consultant  1400
449       437  William Johnson      784     Sales Manager  2500
465       444        Zoe Green      284  Sales consultant  1400
466       444        Zoe Green      284     Sales Manager  2500

Tudo certo com os valores de Role, Wage, Seller, IdSeller e o tipo de dado também foi validado, apesar de preferir os salários como float, manterei Int pois não há casas decimais. Mas há 3 linhas duplicadas com o mesmo IDSeller. Como o natural é a pessoa ser promovida e não o contrário, vou manter apenas as linhas de Manager para esses IDSeller.

In [ ]:
consultores = consultores[
    (consultores["Role"] == "Sales Manager") |
    (~consultores["IdSeller"].duplicated(keep=False))
]

In [ ]:
consultores["IdSeller"].duplicated().sum()
consultores['Role'].value_counts()

Role
Sales consultant    423
Sales Manager        47
Name: count, dtype: int64

**Tratamento Metas**

In [ ]:
metas.head()

   IdStore       Date  Week  RevenueTarget
0      319 2024-03-31    14          11869
1      320 2024-03-31    14          24925
2      321 2024-03-31    14          10682
3      322 2024-03-31    14          10682
4      332 2024-03-31    14          17804

In [ ]:
metas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1222 entries, 0 to 1221
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   IdStore        1222 non-null   int64
 1   Date           1222 non-null   datetime64[ns]
 2   Week           1222 non-null   int64
 3   RevenueTarget  1222 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 38.3 KB

In [ ]:
metas.isnull().sum()

IdStore          0
Date             0
Week             0
RevenueTarget    0
dtype: int64

In [ ]:
metas.duplicated(subset=["IdStore", "Date"], keep=False)

0       False
1       False
2       False
3       False
4       False
        ...
1217    False
1218    False
1219    False
1220    False
1221    False
Length: 1222, dtype: bool

Metas organizadas por semana, chequei apenas se haviam datas duplicadas de acordo com o ID da loja, para somar a Meta, mas não há. Então consider os dados tratados.

**Tratamento de vendas**

In [ ]:
vendas1T.head()

   IdStore       Date  IdPurchase  IdSeller  Quantity  Price
0      784 2024-01-02         438       446         2  94.90
1      784 2024-01-02         440       446         1  47.45
2      784 2024-01-02         440       446         1  47.45
3      784 2024-01-02         436       284         2  94.90
4      784 2024-01-02         437       284         1  52.90

In [ ]:
vendas2T.head()

   IdStore       Date  IdPurchase  IdSeller  Quantity  Price
0     1046 2024-06-29         449       272         1  46.63
1     1046 2024-06-29         449       272         1  46.64
2     1046 2024-06-29         449       272         1  46.63
3     1046 2024-06-29         436       221         1  49.95
4     1046 2024-06-29         436       221         1  49.95

In [ ]:
vendas1T.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99390 entries, 0 to 99389
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IdStore     99390 non-null  int64
 1   Date        99390 non-null  datetime64[ns]
 2   IdPurchase  99390 non-null  int64
 3   IdSeller    99390 non-null  int64
 4   Quantity    99390 non-null  int64
 5   Price       99390 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(4)
memory usage: 4.5 MB

In [ ]:
vendas1T["Date"] = pd.to_datetime(vendas1T["Date"], errors="coerce")
vendas2T["Date"] = pd.to_datetime(vendas2T["Date"], errors="coerce")

In [ ]:
vendas_total = pd.concat([vendas1T, vendas2T], ignore_index=True)

In [ ]:
vendas_total.head()

   IdStore       Date  IdPurchase  IdSeller  Quantity  Price
0      784 2024-01-02         438       446         2  94.90
1      784 2024-01-02         440       446         1  47.45
2      784 2024-01-02         440       446         1  47.45
3      784 2024-01-02         436       284         2  94.90
4      784 2024-01-02         437       284         1  52.90

In [ ]:
vendas_total.isnull().sum()

IdStore       0
Date          0
IdPurchase    0
IdSeller      0
Quantity      0
Price         0
dtype: int64

In [ ]:
vendas_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260068 entries, 0 to 260067
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   IdStore     260068 non-null  int64
 1   Date        260068 non-null  datetime64[ns]
 2   IdPurchase  260068 non-null  int64
 3   IdSeller    260068 non-null  int64
 4   Quantity    260068 non-null  int64
 5   Price       260068 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(4)
memory usage: 11.9 MB

In [ ]:
vendas_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260068 entries, 0 to 260067
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   IdStore     260068 non-null  int64
 1   Date        260068 non-null  datetime64[ns]
 2   IdPurchase  260068 non-null  int64
 3   IdSeller    260068 non-null  int64
 4   Quantity    260068 non-null  int64
 5   Price       260068 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(4)
memory usage: 11.9 MB

In [ ]:
vendas_total["IdPurchase"].duplicated().sum()

np.int64(235743)

Levo em conta que o IdPurchase é o indice de uma compra inteira, cada compra tem um ID, uma quantidade de itens e valores diferentes, então não faz sentido apagar as duplicadas nesse caso.

**Tratando as datas**

Para análise temporal, separo as datas em colunas.

In [ ]:
vendas_total["Date"] = pd.to_datetime(vendas_total["Date"])
vendas_total["Year"] = vendas_total["Date"].dt.year
vendas_total["Month"] = vendas_total["Date"].dt.month
vendas_total["Quarter"] = "T" + vendas_total["Date"].dt.quarter.astype(str)
vendas_total["Week"] = vendas_total["Date"].dt.isocalendar().week.astype(int)

Criei a coluna de quarter, porque eu já fiz essa tratativa de dados de data algumas vezes e quando eu montei o dash, pensei em olhar por trimestre no filtro, em vez de semana, mas acabei olhando o mês, deixei ela na planilha porque pooderia ser útil.

In [ ]:
metas["Date"] = pd.to_datetime(metas["Date"])
metas["Year"] = metas["Date"].dt.year
metas["Month"] = metas["Date"].dt.month
metas["Quarter"] = "T" + metas["Date"].dt.quarter.astype(str)
metas["Week"] = metas["Date"].dt.isocalendar().week.astype(int)

Separei as datas no python, mas também seria possível fazer lá dentro. Isso permite trabalhar os gráficos por tempo.

In [ ]:
vendas_total.head()

,IdStore,Date,IdPurchase,IdSeller,Quantity,Price,Year,Month,Quarter,Week
0,784,2024-01-02,438,446,2,94.90,2024,1,T1,1
1,784,2024-01-02,440,446,1,47.45,2024,1,T1,1
2,784,2024-01-02,440,446,1,47.45,2024,1,T1,1
3,784,2024-01-02,436,284,2,94.90,2024,1,T1,1
4,784,2024-01-02,437,284,1,52.90,2024,1,T1,1

In [ ]:
metas.head()

   IdStore       Date  Week  RevenueTarget  Year  Month Quarter
0      319 2024-03-31    13          11869  2024      3      T1
1      320 2024-03-31    13          24925  2024      3      T1
2      321 2024-03-31    13          10682  2024      3      T1
3      322 2024-03-31    13          10682  2024      3      T1
4      332 2024-03-31    13          17804  2024      3      T1

In [ ]:
vendas_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260068 entries, 0 to 260067
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   IdStore     260068 non-null  int64
 1   Date        260068 non-null  datetime64[ns]
 2   IdPurchase  260068 non-null  int64
 3   IdSeller    260068 non-null  int64
 4   Quantity    260068 non-null  int64
 5   Price       260068 non-null  float64
 6   Year        260068 non-null  int32
 7   Month       260068 non-null  int32
 8   Quarter     260068 non-null  object
 9   Week        260068 non-null  int64
dtypes: datetime64[ns](1), float64(1), int32(2), int64(5), object(1)
memory usage: 17.9+ MB

In [ ]:
vendas_total["Price"] = vendas_total["Price"].astype(float)
vendas_total.head()

,IdStore,Date,IdPurchase,IdSeller,Quantity,Price,Year,Month,Quarter,Week
0,784,2024-01-02,438,446,2,94.90,2024,1,T1,1
1,784,2024-01-02,440,446,1,47.45,2024,1,T1,1
2,784,2024-01-02,440,446,1,47.45,2024,1,T1,1
3,784,2024-01-02,436,284,2,94.90,2024,1,T1,1
4,784,2024-01-02,437,284,1,52.90,2024,1,T1,1

In [ ]:
print(vendas1T.columns)
print(vendas2T.columns)

Index(['IdStore', 'Date', 'IdPurchase', 'IdSeller', 'Quantity', 'Price'], dtype='object')
Index(['IdStore', 'Date', 'IdPurchase', 'IdSeller', 'Quantity', 'Price'], dtype='object')

In [ ]:
vendas_total.to_excel("vendas_total.xlsx", index=False)
consultores.to_excel("consultores_ok.xlsx", index=False)
lojas.to_excel("lojas_ok.xlsx", index=False)
metas.to_excel("metas_ok.xlsx", index=False)

In [ ]:
from google.colab import files

In [ ]:
files.download("vendas_total.xlsx")
files.download("consultores_ok.xlsx")
files.download("lojas_ok.xlsx")
files.download("metas_ok.xlsx")